# Generated by Django 5.0.2 on 2024-02-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='Модель')),
                ('image', models.CharField(max_length=300, verbose_name='Изображение')),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('release_date', models.DateTimeField(verbose_name='Дата релиза')),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
